### PR TITLE
Add "Working with project" chapter, remove all INEUM-related references from usage guide

### PR DESCRIPTION
**Pull request by Surkovsv**
add figures numeration using built-in sphinx-numfig. Screenshots updated.

### CODE REVIEW

**Comment by jubnzv** [comment]
Awesome work!

I'm sorry, but right now I'm not ready to merge your changes, because our local version of this documentation has been changed and heavily reformatted. This will take time (for me) to remove INEUM-related chapters from our new docs and upload them here.

If you interested with it, I can take this work, and we could synchronize our efforts later. What do you say?

**Comment by AndreySV** [comment]
Hi Georgy,
that's sad that we out of sync and our work is lost.  If it will help you, then we can send you 'docx' document with all our changes (updated screenshots and rewrite of INEUM-specified parts).
Our rewritten version is already ready to be used as basis for upstream Beremiz documentation. 
What's your plan for this RST documentation? Are you going to working further on this documentation? Will you benefit from merging your changes in?

**Comment by jubnzv** [comment]
Hi Andrey,

> What's your plan for this RST documentation? Are you going to working further on this documentation? Will you benefit from merging your changes in?

First of all, my interest is to improve quality of our internal documentation, that we gradually working on in INEUM. So I can separate common part related to open-source version of Beremiz out of our docs, merge it with your changes and upload it here to further work with it together. But it takes time, I can do this, say, not earler than at this weekend.

> If it will help you, then we can send you 'docx' document with all our changes (updated screenshots and rewrite of INEUM-specified parts).

Maybe this will be helpful.

**Comment by AndreySV** [comment]
Let's do that. No hurry, take your time.
[usage_guide.docx](https://github.com/sm1820/beremiz/files/2309330/usage_guide.docx)

**Comment by jubnzv** [comment]
It will simpler for me adapt our local docs to this `usage_guide` section, so in this repo I just apply this PR. Which tools are you using to write this documentation? It looks like manually converted `.docx`.

**Comment by AndreySV** [comment]
AFAIK docx was converted using pandoc to rst, afterwards Sergey has used his python script to automaticly fix images and numeration. And most likely some manual changes were done afterwards. He could tell you more about the process, but he is on vacation now. :-)

**Pull request merged**
